### ISSUE TITLE
Can't have it working on neovim

### ISSUE THREAD

**Issue by mikaoelitiana** [paulkass/jira-vim#44]
**Describe the bug**
The plugin doesn't work on neovim. I have the following error : 

```
Erreur détectée en traitant function <SNR>86_JiraVimIssueOpen[3]..check#CheckStorageSession[5]..load_function#LoadSessionStorage[7]..provider#python3#Call :
ligne   18 :
Error invoking 'python_execute' on channel 3 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/mandrianarijaona/.config/nvim/plugged/jira-vim/plugin/../python/common/sessionObject.py", line 6, in __init__
    self.connection = SessionObject.getConnectionFromVars()
  File "/Users/mandrianarijaona/.config/nvim/plugged/jira-vim/plugin/../python/common/sessionObject.py", line 37, in getConnectionFromVars
    domainName = vim.vars["jiraVimDomainName"].decode("utf-8")
AttributeError: 'str' object has no attribute 'decode'
Erreur détectée en traitant function <SNR>86_JiraVimIssueOpen[6]..provider#python3#Call :
ligne   18 :
Error invoking 'python_execute' on channel 3 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'sessionStorage' is not defined
```

**To Reproduce**
1. Install plugin (I am using vimplug)
2. Set credentials
3. Open a existing issue  with `:JiraVimIssueOpen AAA-1234`

**Expected behavior**
The JIRA issue view should open

**Screenshots**
<img width="643" alt="Capture d’écran 2020-02-03 à 14 41 07" src="https://user-images.githubusercontent.com/674667/73657785-4d587100-4693-11ea-904e-1cc12462e424.png">

**Comment by paulkass** [comment]
Hey @mikaoelitiana , can you post the result of `:help version` from your nvim?

**Comment by paulkass** [comment]
I think I fixed the issue in neovim, update the plugin and try again. It seems like neovim presents variables to python already in a string format instead of byte arra, so there is no need to decode them in neovim.

**Comment by cedricdekimpe** [comment]
I'm experiencing the same issue with neovim 0.4.3.

Let me know if any other information might be of use.

(Originally published at: https://cedric.io/2020/im-experiencing-the-same-issue-with-neovim)

**Comment by paulkass** [comment]
@cedricbousmanne Did you upgrade to version 2.1 of the plugin? If yes, does the issue still persist?

**Comment by cedricdekimpe** [comment]
[@paulkass](https://github.com/paulkass) apparently i'm up to date with the git repository on commit 9d7f536da04c6ebffb019d08546941fb3e70caa3

(Originally published at: https://cedric.io/2020/paulkass-apparently-im-up-to-date-with)
