### ISSUE TITLE
Board name is matched strictly

### ISSUE THREAD

**Issue by ronyclau** [paulkass/jira-vim#46]
**Describe the bug**
JIRA board name is currently expected to match the format of `* Board`. Boards by default are generated with a name which matches such pattern, however users are free to rename a board that doesn't conform to the pattern.

**To Reproduce**
1. Go to JIRA and rename a board with a name which doesn't end with ` Board`.
2. In vim, open the board with `:JiraVimBoardOpen <board name>`
4. Error occurs; please refer to the screenshot.

**Expected behavior**
Should support any board name.

**Screenshots**
<img width="709" alt="Screenshot 2020-02-25 at 11 02 28 PM" src="https://user-images.githubusercontent.com/26790480/75259503-18b77f80-5823-11ea-93e6-6c702b2c55ec.png">

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.3
 - NeoVim v0.5.0-nightly-161-g96059d72e
 - Commit 9d7f536

**Comment by ronyclau** [comment]
I have written a simple fix, ready for PR: https://github.com/paulkass/jira-vim/compare/master...ronyclau:fix/lenient-board-match.

**Comment by paulkass** [comment]
Yeah, sounds great! Make the PR, and I can add a test that would prevent these regressions in the future.
