### ISSUE TITLE
Paginate Get Boards Requests

### ISSUE THREAD

**Issue by celioreyes** [paulkass/jira-vim#52]
**Is your feature request related to a problem? Please describe.**
When searching for the board I wanted to open I wasn't getting a successful return. I checked the plugin code and it looked to what I could understand (never written Python before 😞 ) that it wasn't taking into account paginated Jira API requests. As the company, I work for has 400+ boards in our Jira cloud.

**Describe the solution you'd like**
Paginate API requests and to find all boards.

**Describe alternatives you've considered**
Provide a new vim command `:JiraVimBoardOpenById` that will use the `Get Board by Id` API call to get the specified board. The downside of this is that you'll need to know your board ID before using this command.

**Additional context**
I got this working locally and I could put that PR in if this feature is approved 😄 

If this is already a feature let me know as well so I can make sure to ditch my changes and use that way instead.

**Comment by paulkass** [comment]
Hey @celioreyes , have you tried using the `:JiraVimBoardOpen <board name>` command? 

And yes, feel free to send your pr :heart:

**Comment by celioreyes** [comment]
Hola 👋  @paulkass  - yup when I run `:JiraVimBoardOpen <board name>` it errors out b/c it can't find the board. Once I added the pagination code I was able to pull the board and start navigating our issues.

**Comment by paulkass** [comment]
Ah I see, since it pre-loads all the board names it might miss some with pagination. Thanks for the catch! If you have a PR with a fix, please send it in.
