### ISSUE TITLE
Empty directory tabular leads to error when starting vim

### ISSUE THREAD

**Issue by MaralWa** [paulkass/jira-vim#56]
After I have cloned the repository I had this directory structure in ~/.vim/bundle/jira-vim/
```
autoload/          
CONTRIBUTING.md  
ftplugin/    
LICENSE  
python/    
requirements.txt  
tabular/
CODE_OF_CONDUCT.md  
doc/             
jiravim.svg  
plugin/  
README.md  
syntax/           
test/
```
But directory _jira-vim/tabular/_ is empty. Whenever I start vim _jira-vim/plugin/setup.vim_ fails because it expects _jira-vim-/tabular/plugin/Tabular.vim_.

**Comment by paulkass** [comment]
Hey! Yeah, Tabular is a prerequisite because the way I implemented formatting uses the Tabular plugin. You can find it here: https://github.com/godlygeek/tabular. I think I listed as a pre-requisite in the Github Readme and in the Vim help, but feel free to point where I might have missed it!
